version: '3'


services:
  # Database
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - wpsite

  wordpress:
    image: andreccosta/wordpress-xdebug
    ports:
      - 80:80
      - 9000:9000
    volumes:
      - ./wordpress:/var/www/html
    networks:
      - wpsite
    depends_on:
      - db
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=9000 remote_enable=1
      PHP_EXTENSION_XDEBUG: 1
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root

    
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8181:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    networks:
      - wpsite


networks:
  wpsite:
