version: "3"

services:
  # Database
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - wpsite

  # PHP
  wordpress:
    build: config/
    volumes:
      - ./wordpress:/var/www/html
      - ./.vscode:/var/www/html/.vscode
      - ./config/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    networks:
      - wpsite
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root

  # web server
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./config/default.conf:/etc/nginx/conf.d/default.conf
      - ./wordpress:/var/www/html
    depends_on:
      - wordpress
    networks:
      - wpsite

  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8181:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    networks:
      - wpsite

networks:
  wpsite:
